spring:
  profiles:
    active: <%= databaseType %>
  data:
    rest:
      base-path: /api

server:
  servlet:
    context-path: /

---
spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/<%= appName %>
    username: <%= appName %>
    password: Everis18
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    password: Everis18
    url: jdbc:postgresql://localhost:5432/<%= appName %>
    user: <%= appName %>


---
spring:
  profiles: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:<%= appName %>;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:h2:mem:<%= appName %>;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    user: sa
    locations: classpath:db/migration/h2
    schemas: PUBLIC
